# This config file is meant for settings that affect the whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Github Pages + Jekyll + React
email: michaelachrisco@gmail.com
url: "https://michaelachrisco.github.io/gh-actions-boilerplate-client-react/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ['node_modules']